l_english:     
 #---------------------------------------------
 # Game Configuration
 #---------------------------------------------
 # Decision
 view_game_configuration_title: "£empty_mana£ View Game Configuration"
 view_game_configuration_desc: "View and edit current game configuration settings."
 
 # Event
 wwu_game_configuration.1.title: "Game Configuration"
 wwu_game_configuration.1.desc: "Adjust various parameters to change the configuration of your playthrough."
 wwu_game_configuration.1.option.features: "Toggle Features"
 wwu_game_configuration.1.option.difficulty: "Toggle Difficulty"
 wwu_game_configuration.1.option.content: "Toggle Content"
 wwu_game_configuration.1.option.finalize: "Finalize"
 wwu_game_configuration.1.option.exit: "Exit"
 
 wwu_game_configuration.2.title: "Feature Configuration"
 wwu_game_configuration.2.desc: "Toggle the usage of various mod features.\n[Root.GetState_RacialModifiers]\n[Root.GetState_Magic]\n[Root.GetState_Archaeology]\n[Root.GetState_IsolationMechanics]\n[Root.GetState_FederationToggle]\n[Root.GetState_AllianceRestrictions]\n[Root.GetState_WarcraftFactions]"
 wwu_game_configuration.2.option.racial_modifiers.on: "§GEnable§! Racial Modifiers"
 wwu_game_configuration.2.option.racial_modifiers.off: "§RDisable§! Racial Modifiers"
 wwu_game_configuration.2.option.magic.on: "§GEnable§! Magic Mechanics"
 wwu_game_configuration.2.option.magic.off: "§RDisable§! Magic Mechanics"
 wwu_game_configuration.2.option.archaeology.on: "§GEnable§! Archaeology Mechanics"
 wwu_game_configuration.2.option.archaeology.off: "§RDisable§! Archaeology Mechanics"
 wwu_game_configuration.2.option.isolation.on: "§GEnable§! Isolation Mechanics"
 wwu_game_configuration.2.option.isolation.off: "§RDisable§! Isolation Mechanics"
 wwu_game_configuration.2.option.federations.on: "§GEnable§! Federations"
 wwu_game_configuration.2.option.federations.off: "§RDisable§! Federations"
 wwu_game_configuration.2.option.alliance_restrictions.on: "§GEnable§! Alliance Restrictions"
 wwu_game_configuration.2.option.alliance_restrictions.off: "§RDisable§! Alliance Restrictions"
 wwu_game_configuration.2.option.factions.on: "§GEnable§! Warcraft Factions"
 wwu_game_configuration.2.option.factions.off: "§RDisable§! Warcraft Factions"
 wwu_game_configuration.2.option.exit: "Return"
 
 wwu_game_configuration.3.title: "Difficulty Configuration"
 wwu_game_configuration.3.desc: "Toggle the difficulty of the playthrough.\n[Root.GetState_Vanquisher]"
 wwu_game_configuration.3.option.vanquisher.on: "§GEnable§! Vanquisher System"
 wwu_game_configuration.3.option.vanquisher.off: "§RDisable§! Vanquisher System"
 wwu_game_configuration.3.option.exit: "Return"
 
 wwu_game_configuration.4.title: "Content Configuration"
 wwu_game_configuration.4.desc: "Toggle the usage of various continents and the nations they contain. This is aimed at those that want to reduce the amount of nations present during a game, allowing the game to run smoother.\n[Root.GetState_ContentEasternKingdoms]\n[Root.GetState_ContentKalimdor]\n[Root.GetState_ContentNorthrend]\n[Root.GetState_ContentPandaria]\n[Root.GetState_ContentOutland]\n[Root.GetState_ContentDraenor]\n[Root.GetState_ContentBrokenIsles]\n[Root.GetState_ContentZandalar]\n[Root.GetState_ContentKulTiras]\n[Root.GetState_ContentNagaDomain]\n[Root.GetState_ContentParadiseIsles]\n[Root.GetState_ContentSouthSeas]\n[Root.GetState_ContentPlunderIsle]\n[Root.GetState_ContentDragonIsles]\n[Root.GetState_ContentElementalRealms]\n[Root.GetState_ContentArgus]\n[Root.GetState_ContentShadowlands]\n\nThe content if disabled will only be removed when you select Finalize. Do note that the game will hang during this process."
 wwu_game_configuration.4.option.eastern_kingdoms.on: "§GEnable§! Eastern Kingdoms"
 wwu_game_configuration.4.option.eastern_kingdoms.off: "§RDisable§! Eastern Kingdoms"
 wwu_game_configuration.4.option.kalimdor.on: "§GEnable§! Kalimdor"
 wwu_game_configuration.4.option.kalimdor.off: "§RDisable§! Kalimdor"
 wwu_game_configuration.4.option.northrend.on: "§GEnable§! Northrend"
 wwu_game_configuration.4.option.northrend.off: "§RDisable§! Northrend"
 wwu_game_configuration.4.option.pandaria.on: "§GEnable§! Pandaria"
 wwu_game_configuration.4.option.pandaria.off: "§RDisable§! Pandaria"
 wwu_game_configuration.4.option.outland.on: "§GEnable§! Outland"
 wwu_game_configuration.4.option.outland.off: "§RDisable§! Outland"
 wwu_game_configuration.4.option.draenor.on: "§GEnable§! Draenor"
 wwu_game_configuration.4.option.draenor.off: "§RDisable§! Draenor"
 wwu_game_configuration.4.option.broken_isles.on: "§GEnable§! Broken Isles"
 wwu_game_configuration.4.option.broken_isles.off: "§RDisable§! Broken Isles"
 wwu_game_configuration.4.option.zandalar.on: "§GEnable§! Zandalar"
 wwu_game_configuration.4.option.zandalar.off: "§RDisable§! Zandalar"
 wwu_game_configuration.4.option.kul_tiras.on: "§GEnable§! Kul Tiras"
 wwu_game_configuration.4.option.kul_tiras.off: "§RDisable§! Kul Tiras"
 wwu_game_configuration.4.option.naga_domain.on: "§GEnable§! Vash'jir & Nazjatar"
 wwu_game_configuration.4.option.naga_domain.off: "§RDisable§! Vash'jir & Nazjatar"
 wwu_game_configuration.4.option.paradise_isles.on: "§GEnable§! Paradise Isles"
 wwu_game_configuration.4.option.paradise_isles.off: "§RDisable§! Paradise Isles"
 wwu_game_configuration.4.option.south_seas.on: "§GEnable§! South Sea Islands"
 wwu_game_configuration.4.option.south_seas.off: "§RDisable§! South Sea Islands"
 wwu_game_configuration.4.option.plunder_isle.on: "§GEnable§! Plunder Isle"
 wwu_game_configuration.4.option.plunder_isle.off: "§RDisable§! Plunder Isle"
 wwu_game_configuration.4.option.dragon_isles.on: "§GEnable§! Dragon Isles"
 wwu_game_configuration.4.option.dragon_isles.off: "§RDisable§! Dragon Isles"
 wwu_game_configuration.4.option.elemental_realms.on: "§GEnable§! Elemental Realms"
 wwu_game_configuration.4.option.elemental_realms.off: "§RDisable§! Elemental Realms"
 wwu_game_configuration.4.option.argus.on: "§GEnable§! Argus"
 wwu_game_configuration.4.option.argus.off: "§RDisable§! Argus"
 wwu_game_configuration.4.option.shadowlands.on: "§GEnable§! Shadowlands"
 wwu_game_configuration.4.option.shadowlands.off: "§RDisable§! Shadowlands"
 wwu_game_configuration.4.option.exit: "Return"
 
 # Tooltips
 FINALIZE_CONFIG_TT: "This will remove the Game Configuration decision and finalize your settings for the playthrough."
 
 ISOLATION_ON_TT: "Enable Isolation mechanics, which restrict diplomatic interactions for and with nations that are Isolated."
 ISOLATION_OFF_TT: "Disable Isolation mechanics, which restrict diplomatic interactions for and with nations that are Isolated."
 
 FEDERATIONS_ON_TT: "Enable the ability to form Federations, which act as an additional alliance network for native governments."
 FEDERATIONS_OFF_TT: "Disable the ability to form Federations, which act as an additional alliance network for native governments."
 
 ALLIANCE_RESTRICTIONS_ON_TT: "Enable restrictions to Alliances based on lore."
 ALLIANCE_RESTRICTIONS_OFF_TT: "Disable restrictions to Alliances based on lore."
 
 RACIAL_MODIFIERS_ON_TT: "Enable Racial Administration and Military modifiers."
 RACIAL_MODIFIERS_OFF_TT: "Disable Racial Administration and Military modifiers."
 
 MAGIC_ON_TT: "Enable Magic mechanics, which cover ruler spellcasting."
 MAGIC_OFF_TT: "Disable Magic mechanics, which cover ruler spellcasting."
 
 ARCHAEOLOGY_ON_TT: "Enable Archaeology mechanics, which covers excavation and artifacts."
 ARCHAEOLOGY_OFF_TT: "Disable Archaeology mechanics, which covers excavation and artifacts."
 
 VANQUISHER_ON_TT: "Enable the Vanquisher system, which randomly grants AI bonuses that allow them to become more of a threat to the player."
 VANQUISHER_OFF_TT: "Disable the Vanquisher system, which randomly grants AI bonuses that allow them to become more of a threat to the player."
 
 FACTIONS_ON_TT: "Enable the Warcraft Faction system, which represents the Alliance, the Horde and the Old Horde."
 FACTIONS_OFF_TT: "Disable the Warcraft Faction system, which represents the Alliance, the Horde and the Old Horde."
 
 EASTERN_KINGDOMS_ON_TT: "Enable the Eastern Kingdoms."
 EASTERN_KINGDOMS_OFF_TT: "Disable the Eastern Kingdoms."
 
 KALIMDOR_ON_TT: "Enable Kalimdor."
 KALIMDOR_OFF_TT: "Disable Kalimdor."
 
 NORTHREND_ON_TT: "Enable Northrend."
 NORTHREND_OFF_TT: "Disable Northrend."
 
 PANDARIA_ON_TT: "Enable Pandaria."
 PANDARIA_OFF_TT: "Disable Pandaria."
 
 OUTLAND_ON_TT: "Enable Outland."
 OUTLAND_OFF_TT: "Disable Outland."
 
 DRAENOR_ON_TT: "Enable Draenor."
 DRAENOR_OFF_TT: "Disable Draenor."
 
 BROKEN_ISLES_TT: "Enable the Broken Isles."
 BROKEN_ISLES_OFF_TT: "Disable the Broken Isles."
 
 ZANDALAR_ON_TT: "Enable Zandalar."
 ZANDALAR_OFF_TT: "Disable Zandalar."
 
 KUL_TIRAS_ON_TT: "Enable Kul Tiras."
 KUL_TIRAS_OFF_TT: "Disable Kul Tiras."
 
 NAGA_DOMAIN_ON_TT: "Enable Vash'jir & Nazjatar."
 NAGA_DOMAIN_OFF_TT: "Disable Vash'jir & Nazjatar."
 
 PARADISE_ISLES_ON_TT: "Enable the Paradise Isles."
 PARADISE_ISLES_OFF_TT: "Disable the Paradise Isles."
 
 SOUTH_SEAS_ON_TT: "Enable the South Sea Islands."
 SOUTH_SEAS_OFF_TT: "Disable the South Sea Islands."
 
 PLUNDER_ISLE_ON_TT: "Enable Plunder Isle."
 PLUNDER_ISLE_OFF_TT: "Disable Plunder Isle."
 
 DRAGON_ISLES_ON_TT: "Enable the Dragon Isles."
 DRAGON_ISLES_OFF_TT: "Disable the Dragon Isles."
 
 ELEMENTAL_REALMS_ON_TT: "Enable the Elemental Realms."
 ELEMENTAL_REALMS_OFF_TT: "Disable the Elemental Realms."
 
 ARGUS_ON_TT: "Enable Argus."
 ARGUS_OFF_TT: "Disable Argus."
 
 SHADOWLANDS_ON_TT: "Enable Shadowlands."
 SHADOWLANDS_OFF_TT: "Disable Shadowlands."
 
 # Flags
 enabled_isolation_mechanics: "Enabled Isolation Mechanics"
 enabled_federations: "Enabled Federations"
 enabled_lore_diplomacy_mechanics: "Enabled Lore-based Alliance Restrictions"
 enabled_racial_modifiers: "Enabled Racial Modifiers"
 enabled_magic_mechanics: "Enabled Magic Mechanics"
 enabled_archaeology_mechanics: "Enabled Archaeology Mechanics"
 enabled_faction_mechanics: "Enabled Warcraft Faction Mechanics"
 
 enabled_vanquisher_system: "Enabled Vanquisher System"
 
 enable_content_eastern_kingdoms: "Enabled Eastern Kingdoms content"
 enable_content_kalimdor: "Enabled Kalimdor content"
 enable_content_northrend: "Enabled Northrend content"
 enable_content_pandaria: "Enabled Pandaria content"
 enable_content_outland: "Enabled Outland content"
 enable_content_draenor: "Enabled Draenor content"
 enable_content_broken_isles: "Enabled Broken Isles content"
 enable_content_zandalar: "Enabled Zandalar content"
 enable_content_kul_tiras: "Enabled Kul Tiras content"
 enable_content_naga_domain: "Enabled Vash'jir & Nazjatar content"
 enable_content_paradise_isles: "Enabled Paradise Isles content"
 enable_content_south_seas: "Enabled South Sea Islands content"
 enable_content_plunder_isle: "Enabled Plunder Isle content"
 enable_content_dragon_isles: "Enabled Dragon Isles content"
 enable_content_elemental_realms: "Enabled Elemental Realm content"
 enable_content_argus: "Enabled Argus content"
 enable_content_shadowlands: "Enabled Shadowlands content"
 
 # Strings
 DISABLED_MECHANIC: "Disabled"
 
 ISOLATION_MECHANICS_ON: "Isolation Mechanics: §GON§!"
 ISOLATION_MECHANICS_OFF: "Isolation Mechanics: §ROFF§!"
 
 FEDERATION_TOGGLE_ON: "Allow Federations: §GON§!"
 FEDERATION_TOGGLE_OFF: "Allow Federations: §ROFF§!"
 
 ALLIANCE_RESTRICTIONS_ON: "Enforce Alliance Restrictions: §GON§!"
 ALLIANCE_RESTRICTIONS_OFF: "Enforce Alliance Restrictions: §ROFF§!"
 
 RACIAL_MODIFIERS_ON: "Racial Modifiers: §GON§!"
 RACIAL_MODIFIERS_OFF: "Racial Modifiers: §ROFF§!"
 
 MAGIC_MECHANICS_ON: "Magic Mechanics: §GON§!"
 MAGIC_MECHANICS_OFF: "Magic Mechanics: §ROFF§!"
 
 ARCHAEOLOGY_MECHANICS_ON: "Archaeology Mechanics: §GON§!"
 ARCHAEOLOGY_MECHANICS_OFF: "Archaeology Mechanics: §ROFF§!"
 
 VANQUISHER_SYSTEM_ON: "Vanquisher System: §GON§!"
 VANQUISHER_SYSTEM_OFF: "Vanquisher System: §ROFF§!"
 
 WARCRAFT_FACTIONS_ON: "Warcraft Faction System: §GON§!"
 WARCRAFT_FACTIONS_OFF: "Warcraft Faction System: §ROFF§!"
 
 # Content
 EASTERN_KINGDOMS_ON: "Eastern Kingdoms: §GON§!"
 EASTERN_KINGDOMS_OFF: "Eastern Kingdoms: §ROFF§!"
 
 KALIMDOR_ON: "Kalimdor: §GON§!"
 KALIMDOR_OFF: "Kalimdor: §ROFF§!"
 
 NORTHREND_ON: "Northrend: §GON§!"
 NORTHREND_OFF: "Northrend: §ROFF§!"
 
 PANDARIA_ON: "Pandaria: §GON§!"
 PANDARIA_OFF: "Pandaria: §ROFF§!"
 
 OUTLAND_ON: "Outland: §GON§!"
 OUTLAND_OFF: "Outland: §ROFF§!"
 
 DRAENOR_ON: "Draenor: §GON§!"
 DRAENOR_OFF: "Draenor: §ROFF§!"
 
 BROKEN_ISLES_ON: "Broken Isles: §GON§!"
 BROKEN_ISLES_OFF: "Broken Isles: §ROFF§!"
 
 ZANDALAR_ON: "Zandalar: §GON§!"
 ZANDALAR_OFF: "Zandalar: §ROFF§!"
 
 KUL_TIRAS_ON: "Kul Tiras: §GON§!"
 KUL_TIRAS_OFF: "Kul Tiras: §ROFF§!"
 
 NAGA_DOMAIN_ON: "Vash'jir & Nazjatar: §GON§!"
 NAGA_DOMAIN_OFF: "Vash'jir & Nazjatar: §ROFF§!"
 
 PARADISE_ISLES_ON: "Paradise Isles: §GON§!"
 PARADISE_ISLES_OFF: "Paradise Isles: §ROFF§!"
 
 SOUTH_SEAS_ON: "South Sea Islands: §GON§!"
 SOUTH_SEAS_OFF: "South Sea Islands: §ROFF§!"
 
 PLUNDER_ISLE_ON: "Plunder Isle: §GON§!"
 PLUNDER_ISLE_OFF: "Plunder Isle: §ROFF§!"
 
 DRAGON_ISLES_ON: "Dragon Isles: §GON§!"
 DRAGON_ISLES_OFF: "Dragon Isles: §ROFF§!"
 
 ELEMENTAL_REALMS_ON: "Elemental Realms: §GON§!"
 ELEMENTAL_REALMS_OFF: "Elemental Realms: §ROFF§!"
 
 ARGUS_ON: "Argus: §GON§!"
 ARGUS_OFF: "Argus: §ROFF§!"
 
 SHADOWLANDS_ON: "Shadowlands: §GON§!"
 SHADOWLANDS_OFF: "Shadowlands: §ROFF§!"
 
 # Misc
 vanquisher_personality: "Vanquisher"
 desc_vanquisher_personality: ""
 
 vanquisher_bonus: "Vanquisher"
 desc_vanquisher_bonus: ""